# Generated by Django 6.0.1 on 2026-01-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_visualization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisresult",
            name="user",
        ),
        migrations.RemoveField(
            model_name="visualization",
            name="user",
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="user_id",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualization",
            name="user_id",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
