# Generated by Django 6.0.1 on 2026-01-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_analysisresult_user_remove_visualization_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                (
                    "title",
                    models.CharField(default="Untitled Analysis", max_length=255),
                ),
                ("data_points", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                ("tab_type", models.CharField(default="regression", max_length=20)),
                (
                    "regression_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("polynomial_degree", models.IntegerField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "draft_analyses",
                "ordering": ["-updated_at"],
            },
        ),
    ]
