# Generated by Django 6.0.1 on 2026-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_draftanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualization",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="chart_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="csv_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="data_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
