# Generated by Django 5.2.10 on 2026-01-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visualization_ai_summary_visualization_chart_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('page_type', models.CharField(choices=[('categorical', 'Categorical Chat'), ('regression', 'Regression Plot'), ('curve', 'Curve Plot')], max_length=50)),
                ('state_data', models.JSONField()),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_sessions',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user_id', 'page_type'], name='page_sessio_user_id_5bddc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('page_type', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'page_type', 'created_at'], name='user_histor_user_id_e211e3_idx')],
            },
        ),
    ]
