# Generated by Django 5.2.10 on 2026-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workspace_analysisresult_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visualization',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
