# Generated by Django 5.2.10 on 2026-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_analysisresult_is_public_visualization_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deleted_sync_records',
            },
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='draftanalysis',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pagesession',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visualization',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
