# Generated by Django 6.0.2 on 2026-02-13 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the todo item",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Title must not be empty"
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the todo",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether the todo is completed"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Priority level of the todo",
                        max_length=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional due date for the todo",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when todo was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when todo was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
                "ordering": ["-created_at"],
            },
        ),
    ]
