# Generated by Django 5.2.10 on 2026-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pending_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
